
/* Generated by ai2jsx v0.89.0 - 2019-07-11 12:53 */
/* ai file: Graph.ai */

import React from 'react';
import { styles } from './styles.scss';

const mobile = () => (
  <div className={`mobile ${styles}`}>
    <div id='g-mobile-box'>
      <div id='g-Graph-mobile' className='g-artboard' style={{ width: '300px', height: '284.348750000001px' }} data-aspect-ratio='1.055' data-min-width='300' data-max-width='719'>
        <img id='g-Graph-mobile-img' className='g-aiImg g-aiAbs' alt='' src='./Graph-mobile.png' />
        <div id='g-ai1-1' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '6.9066%', marginTop: '-19.6px', left: '-0.0215%', width: '272px' }}>
          <p className='g-pstyle0'>In his re-election race, Mayor Pete</p>
          <p className='g-pstyle0'>lost support in black neighborhoods</p>
        </div>
        <div id='g-ai1-2' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '21.2261%', marginTop: '-15.4px', left: '-0.0215%', width: '293px' }}>
          <p className='g-pstyle1'>Average shift in Buttigieg&rsquo;s general election margin,</p>
          <p className='g-pstyle1'>by share of black residents in precinct</p>
        </div>
        <div id='g-ai1-3' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '34.7776%', marginTop: '-8.9px', left: '6.6152%', marginLeft: '-26.5px', width: '53px' }}>
          <p className='g-pstyle2'>+12%</p>
        </div>
        <div id='g-ai1-4' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '36.8943%', marginTop: '-6.9px', left: '69.8841%', marginLeft: '-67.5px', width: '135px' }}>
          <p className='g-pstyle3'>MORE BLACK RESIDENTS</p>
        </div>
        <div id='g-ai1-5' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '38.6461%', marginTop: '-8.9px', left: '21.0557%', marginLeft: '-26.5px', width: '53px' }}>
          <p className='g-pstyle2'>+10%</p>
        </div>
        <div id='g-ai1-6' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '50.6032%', marginTop: '-8.9px', left: '35.5583%', marginLeft: '-23px', width: '46px' }}>
          <p className='g-pstyle2'>+5%</p>
        </div>
        <div id='g-ai1-7' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '50.6032%', marginTop: '-8.9px', left: '50.0137%', marginLeft: '-23px', width: '46px' }}>
          <p className='g-pstyle2'>+5%</p>
        </div>
        <div id='g-ai1-8' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '60.1876%', marginTop: '-12.1px', left: '64.4391%', marginLeft: '-27px', width: '54px' }}>
          <p className='g-pstyle4'>40-50%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai1-9' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '60.1876%', marginTop: '-12.1px', left: '78.8945%', marginLeft: '-27px', width: '54px' }}>
          <p className='g-pstyle4'>50-60%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai1-10' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '60.1876%', marginTop: '-12.1px', left: '93.3496%', marginLeft: '-27px', width: '54px' }}>
          <p className='g-pstyle4'>60-70%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai1-11' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '71.0897%', marginTop: '-12.1px', left: '6.5827%', marginLeft: '-24.5px', width: '49px' }}>
          <p className='g-pstyle4'>0-10%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai1-12' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '71.0897%', marginTop: '-12.1px', left: '20.9889%', marginLeft: '-27px', width: '54px' }}>
          <p className='g-pstyle4'>10-20%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai1-13' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '71.0897%', marginTop: '-12.1px', left: '35.4863%', marginLeft: '-27px', width: '54px' }}>
          <p className='g-pstyle4'>20-30%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai1-14' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '71.0897%', marginTop: '-12.1px', left: '49.9417%', marginLeft: '-27px', width: '54px' }}>
          <p className='g-pstyle4'>30-40%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai1-15' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '74.1658%', marginTop: '-8.9px', left: '64.4111%', marginLeft: '-22.5px', width: '45px' }}>
          <p className='g-pstyle2'>&ndash;2%</p>
        </div>
        <div id='g-ai1-16' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '79.0894%', marginTop: '-8.9px', left: '93.3216%', marginLeft: '-22.5px', width: '45px' }}>
          <p className='g-pstyle2'>&ndash;4%</p>
        </div>
        <div id='g-ai1-17' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '98.4318%', marginTop: '-8.9px', left: '78.8685%', marginLeft: '-26px', width: '52px' }}>
          <p className='g-pstyle2'>&ndash;12%</p>
        </div>
      </div>
    </div>
  </div>
);

export default mobile;
/* End ai2jsx - 2019-07-11 12:53 */
