
/* Generated by ai2jsx v0.89.0 - 2019-07-12 12:20 */
/* ai file: Map.ai */

import React from 'react';
import { styles } from './styles.scss';

const md = () => (
  <div className={`md ${styles}`}>
    <div id='g-md-box'>
      <div id='g-Map-md' className='g-artboard' style={{ width: '658px', height: '543.287222222221px' }} data-aspect-ratio='1.211' data-min-width='658' data-max-width='849'>
        <img id='g-Map-md-img' className='g-aiImg g-aiAbs' alt='' src='./Map-md.png' />
        <div id='g-ai0-1' className='g-ai2jsx-settings g-aiAbs g-aiPointText' style={{ top: '-5.2201%', marginTop: '-15.6px', left: '0%', width: '112px' }}>
          <p className='g-pstyle0'>658</p>
        </div>
        <div id='g-ai0-2' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '5.1868%', marginTop: '-24.2px', left: '23.5861%', marginLeft: '-157px', width: '314px' }}>
          <p className='g-pstyle1'>Change in Buttigieg&rsquo;s general</p>
          <p className='g-pstyle1'>election margin, 2011-2015</p>
        </div>
        <div id='g-ai0-3' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '5.1868%', marginTop: '-24.2px', left: '75.9039%', marginLeft: '-161.5px', width: '323px' }}>
          <p className='g-pstyle1'>Vacant and abandoned houses</p>
          <p className='g-pstyle1'>targeted by the initiative</p>
        </div>
        <div id='g-ai0-4' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '13.3617%', marginTop: '-10.6px', left: '75.9444%', marginLeft: '-130.5px', width: '261px' }}>
          <p className='g-pstyle2'>As identified by mayor&rsquo;s task force</p>
        </div>
        <div id='g-ai0-5' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '17.7541%', marginTop: '-9.5px', left: '5.4284%', marginLeft: '-27.5px', width: '55px' }}>
          <p className='g-pstyle3'>&ndash;40%</p>
        </div>
        <div id='g-ai0-6' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '17.7541%', marginTop: '-9.5px', left: '14.7456%', marginLeft: '-27.5px', width: '55px' }}>
          <p className='g-pstyle3'>&ndash;20%</p>
        </div>
        <div id='g-ai0-7' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '17.7541%', marginTop: '-9.5px', left: '24.0978%', marginLeft: '-20px', width: '40px' }}>
          <p className='g-pstyle3'>0%</p>
        </div>
        <div id='g-ai0-8' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '17.7541%', marginTop: '-9.5px', left: '33.1763%', marginLeft: '-27.5px', width: '55px' }}>
          <p className='g-pstyle3'>+20%</p>
        </div>
        <div id='g-ai0-9' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '17.7541%', marginTop: '-9.5px', left: '41.9703%', marginLeft: '-27.5px', width: '55px' }}>
          <p className='g-pstyle3'>+40%</p>
        </div>
      </div>
    </div>
  </div>
);

export default md;
/* End ai2jsx - 2019-07-12 12:20 */
