/* eslint-disable max-len */

// Project Statuses
export const STATUS_PROJECT_OK = 'STATUS_PROJECT_OK';
export const STATUS_PROJECT_NOT_GENERATED = 'STATUS_PROJECT_NOT_GENERATED';
export const STATUS_PROJECT_VALID_UPLOAD = 'STATUS_PROJECT_VALID_UPLOAD';
export const STATUS_PROJECT_DOWNLOAD_AVAILABLE = 'STATUS_PROJECT_INVALID_UPLOAD';
export const STATUS_PROJECT_ARCHIVED = 'STATUS_PROJECT_ARCHIVED';
export const STATUS_PROJECT_MISMATCH = 'STATUS_PROJECT_MISMATCH';

// Illustration Statuses
export const STATUS_ILLUSTRATION_OK = 'STATUS_ILLUSTRATION_OK';
export const STATUS_ILLUSTRATION_NOT_GENERATED = 'STATUS_ILLUSTRATION_NOT_GENERATED';
export const STATUS_ILLUSTRATION_VALID_UPLOAD = 'STATUS_ILLUSTRATION_VALID_UPLOAD';
export const STATUS_ILLUSTRATION_DOWNLOAD_AVAILABLE = 'STATUS_ILLUSTRATION_DOWNLOAD_AVAILABLE';
export const STATUS_ILLUSTRATION_ARCHIVED = 'STATUS_ILLUSTRATION_ARCHIVED';

// All statuses for easy type export
export const ALL_STATUSES = [
  STATUS_PROJECT_OK,
  STATUS_PROJECT_NOT_GENERATED,
  STATUS_PROJECT_VALID_UPLOAD,
  STATUS_PROJECT_DOWNLOAD_AVAILABLE,
  STATUS_PROJECT_ARCHIVED,
  STATUS_PROJECT_MISMATCH,
  STATUS_ILLUSTRATION_OK,
  STATUS_ILLUSTRATION_NOT_GENERATED,
  STATUS_ILLUSTRATION_VALID_UPLOAD,
  STATUS_ILLUSTRATION_DOWNLOAD_AVAILABLE,
  STATUS_ILLUSTRATION_ARCHIVED,
];
