/* eslint-disable max-len */

export const STATUS_UNKNOWN = 'STATUS_UNKNOWN';

// TO BE DELETED...
export const STATUS_PROJECT_OK = 'STATUS_PROJECT_OK';
export const STATUS_PROJECT_NOT_GENERATED = 'STATUS_PROJECT_NOT_GENERATED';
export const STATUS_PROJECT_VALID_UPLOAD = 'STATUS_PROJECT_VALID_UPLOAD';
export const STATUS_PROJECT_DOWNLOAD_AVAILABLE = 'STATUS_PROJECT_DOWNLOAD_AVAILABLE';
export const STATUS_PROJECT_ARCHIVED = 'STATUS_PROJECT_ARCHIVED';
export const STATUS_PROJECT_MISMATCH = 'STATUS_PROJECT_MISMATCH';
export const STATUS_ILLUSTRATION_VALID_UPLOAD = 'STATUS_ILLUSTRATION_VALID_UPLOAD';
export const STATUS_ILLUSTRATION_DOWNLOAD_AVAILABLE = 'STATUS_ILLUSTRATION_DOWNLOAD_AVAILABLE';
export const STATUS_ILLUSTRATION_ARCHIVED = 'STATUS_ILLUSTRATION_ARCHIVED';

// Project Statuses
export const STATUS_PROJECT_DRAFT = 'STATUS_PROJECT_DRAFT';
export const STATUS_PROJECT_PUBLISHED = 'STATUS_PROJECT_PUBLISHED';
export const STATUS_PROJECT_CHANGES = 'STATUS_PROJECT_CHANGES';
export const STATUS_PROJECT_UNKNOWN = 'STATUS_PROJECT_UNKNOWN';

// Illustration Statuses
export const STATUS_ILLUSTRATION_OK = 'STATUS_ILLUSTRATION_OK';
export const STATUS_ILLUSTRATION_NOT_GENERATED = 'STATUS_ILLUSTRATION_NOT_GENERATED';

// All statuses for easy type export
export const ALL_STATUSES = [
  STATUS_PROJECT_OK,
  STATUS_PROJECT_NOT_GENERATED,
  STATUS_PROJECT_VALID_UPLOAD,
  STATUS_PROJECT_DOWNLOAD_AVAILABLE,
  STATUS_PROJECT_ARCHIVED,
  STATUS_PROJECT_MISMATCH,
  STATUS_ILLUSTRATION_OK,
  STATUS_ILLUSTRATION_NOT_GENERATED,
  STATUS_ILLUSTRATION_VALID_UPLOAD,
  STATUS_ILLUSTRATION_DOWNLOAD_AVAILABLE,
  STATUS_ILLUSTRATION_ARCHIVED,
  STATUS_PROJECT_DRAFT,
  STATUS_PROJECT_PUBLISHED,
  STATUS_PROJECT_CHANGES,
];
