/* eslint-disable max-len */

export const STATUS_UNKNOWN = 'STATUS_UNKNOWN';

// Project Statuses
export const STATUS_PROJECT_DRAFT = 'STATUS_PROJECT_DRAFT';
export const STATUS_PROJECT_PUBLISHED = 'STATUS_PROJECT_PUBLISHED';
export const STATUS_PROJECT_CHANGES = 'STATUS_PROJECT_CHANGES';
export const STATUS_PROJECT_UNKNOWN = 'STATUS_PROJECT_UNKNOWN';

// Illustration Statuses
export const STATUS_ILLUSTRATION_OK = 'STATUS_ILLUSTRATION_OK';
export const STATUS_ILLUSTRATION_NOT_GENERATED = 'STATUS_ILLUSTRATION_NOT_GENERATED';
export const STATUS_ILLUSTRATION_NONEXISTENT = 'STATUS_ILLUSTRATION_NONEXISTENT';

// All statuses for easy type export
export const ALL_STATUSES = [
  STATUS_PROJECT_DRAFT,
  STATUS_PROJECT_PUBLISHED,
  STATUS_PROJECT_CHANGES,
  STATUS_ILLUSTRATION_OK,
  STATUS_ILLUSTRATION_NOT_GENERATED,
];
