
/* Generated by ai2jsx v0.89.0 - 2019-07-12 12:20 */
/* ai file: Map.ai */

import React from 'react';
import { styles } from './styles.scss';

const lg = () => (
  <div className={`lg ${styles}`}>
    <div id='g-lg-box'>
      <div id='g-Map-lg' className='g-artboard' style={{ width: '850px', height: '704.361702127659px' }} data-aspect-ratio='1.207' data-min-width='850'>
        <img id='g-Map-lg-img' className='g-aiImg g-aiAbs' alt='' src='./Map-lg.png' />
        <div id='g-ai2-1' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '5.7629%', marginTop: '-31.6px', left: '23.6795%', marginLeft: '-201px', width: '402px' }}>
          <p className='g-pstyle0'>Change in Buttigieg&rsquo;s general</p>
          <p className='g-pstyle0'>election margin, 2011-2015</p>
        </div>
        <div id='g-ai2-2' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '5.7629%', marginTop: '-31.6px', left: '76.217%', marginLeft: '-206.5px', width: '413px' }}>
          <p className='g-pstyle0'>Vacant and abandoned houses</p>
          <p className='g-pstyle0'>targeted by the initiative</p>
        </div>
        <div id='g-ai2-3' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '13.8854%', marginTop: '-13.8px', left: '76.2276%', marginLeft: '-166px', width: '332px' }}>
          <p className='g-pstyle1'>As identified by mayor&rsquo;s task force</p>
        </div>
        <div id='g-ai2-4' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '18.361%', marginTop: '-12.3px', left: '5.3278%', marginLeft: '-32px', width: '64px' }}>
          <p className='g-pstyle2'>&ndash;40%</p>
        </div>
        <div id='g-ai2-5' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '18.361%', marginTop: '-12.3px', left: '14.6914%', marginLeft: '-32px', width: '64px' }}>
          <p className='g-pstyle2'>&ndash;20%</p>
        </div>
        <div id='g-ai2-6' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '18.361%', marginTop: '-12.3px', left: '24.1178%', marginLeft: '-22.5px', width: '45px' }}>
          <p className='g-pstyle2'>0%</p>
        </div>
        <div id='g-ai2-7' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '18.361%', marginTop: '-12.3px', left: '33.2136%', marginLeft: '-32px', width: '64px' }}>
          <p className='g-pstyle2'>+20%</p>
        </div>
        <div id='g-ai2-8' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '18.361%', marginTop: '-12.3px', left: '42.0514%', marginLeft: '-32px', width: '64px' }}>
          <p className='g-pstyle2'>+40%</p>
        </div>
      </div>
    </div>
  </div>
);

export default lg;
/* End ai2jsx - 2019-07-12 12:20 */
