
/* Generated by ai2jsx v0.89.0 - 2019-07-11 12:53 */
/* ai file: Graph.ai */

import React from 'react';
import { styles } from './styles.scss';

const desktop = () => (
  <div className={`desktop ${styles}`}>
    <div id='g-desktop-box'>
      <div id='g-Graph-desktop' className='g-artboard' style={{ width: '720px', height: '373.478419452887px' }} data-aspect-ratio='1.928' data-min-width='720'>
        <img id='g-Graph-desktop-img' className='g-aiImg g-aiAbs' alt='' src='./Graph-desktop.png' />
        <div id='g-ai0-1' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '4.5188%', marginTop: '-11.9px', left: '-0.0089%', width: '733px' }}>
          <p className='g-pstyle0'>In his re-election race, Mayor Pete lost support in black neighborhoods</p>
        </div>
        <div id='g-ai0-2' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '13.2112%', marginTop: '-12.3px', left: '-0.0089%', width: '740px' }}>
          <p className='g-pstyle1'>Average shift in Buttigieg&rsquo;s general election margin, by share of black residents in precinct</p>
        </div>
        <div id='g-ai0-3' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '24.8237%', marginTop: '-14.7px', left: '6.6121%', marginLeft: '-36.5px', width: '73px' }}>
          <p className='g-pstyle2'>+12%</p>
        </div>
        <div id='g-ai0-4' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '29.1078%', marginTop: '-14.7px', left: '21.0506%', marginLeft: '-36.5px', width: '73px' }}>
          <p className='g-pstyle2'>+10%</p>
        </div>
        <div id='g-ai0-5' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '30.9121%', marginTop: '-10.4px', left: '80.9807%', marginLeft: '-96.5px', width: '193px' }}>
          <p className='g-pstyle3'>MORE BLACK RESIDENTS</p>
        </div>
        <div id='g-ai0-6' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '43.2987%', marginTop: '-14.7px', left: '35.5221%', marginLeft: '-30.5px', width: '61px' }}>
          <p className='g-pstyle2'>+5%</p>
        </div>
        <div id='g-ai0-7' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '43.2987%', marginTop: '-14.7px', left: '49.9756%', marginLeft: '-30.5px', width: '61px' }}>
          <p className='g-pstyle2'>+5%</p>
        </div>
        <div id='g-ai0-8' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '50.238%', marginTop: '-23.6px', left: '64.5034%', marginLeft: '-40px', width: '80px' }}>
          <p className='g-pstyle4'>40-50%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai0-9' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '50.238%', marginTop: '-23.6px', left: '78.957%', marginLeft: '-40px', width: '80px' }}>
          <p className='g-pstyle4'>50-60%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai0-10' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '50.238%', marginTop: '-23.6px', left: '93.4104%', marginLeft: '-40px', width: '80px' }}>
          <p className='g-pstyle4'>60-70%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai0-11' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '70.8549%', marginTop: '-23.6px', left: '6.5708%', marginLeft: '-35px', width: '70px' }}>
          <p className='g-pstyle4'>0-10%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai0-12' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '70.8549%', marginTop: '-23.6px', left: '21.0586%', marginLeft: '-40px', width: '80px' }}>
          <p className='g-pstyle4'>10-20%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai0-13' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '70.8549%', marginTop: '-23.6px', left: '35.5543%', marginLeft: '-40px', width: '80px' }}>
          <p className='g-pstyle4'>20-30%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai0-14' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '70.8549%', marginTop: '-23.6px', left: '50.0077%', marginLeft: '-40px', width: '80px' }}>
          <p className='g-pstyle4'>30-40%</p>
          <p className='g-pstyle4'>black</p>
        </div>
        <div id='g-ai0-15' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '70.3417%', marginTop: '-14.7px', left: '64.5173%', marginLeft: '-30.5px', width: '61px' }}>
          <p className='g-pstyle2'>&ndash;2%</p>
        </div>
        <div id='g-ai0-16' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '75.9645%', marginTop: '-14.7px', left: '93.4242%', marginLeft: '-30.5px', width: '61px' }}>
          <p className='g-pstyle2'>&ndash;4%</p>
        </div>
        <div id='g-ai0-17' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '98.188%', marginTop: '-14.7px', left: '78.9327%', marginLeft: '-36px', width: '72px' }}>
          <p className='g-pstyle2'>&ndash;12%</p>
        </div>
      </div>
    </div>
  </div>
);

export default desktop;
/* End ai2jsx - 2019-07-11 12:53 */
