
/* Generated by ai2jsx v0.89.0 - 2019-07-12 12:20 */
/* ai file: Map.ai */

import React from 'react';
import { styles } from './styles.scss';

const sm = () => (
  <div className={`sm ${styles}`}>
    <div id='g-sm-box'>
      <div id='g-Map-sm' className='g-artboard' style={{ width: '300px', height: '877.348750000001px' }} data-aspect-ratio='0.342' data-min-width='300' data-max-width='657'>
        <img id='g-Map-sm-img' className='g-aiImg g-aiAbs' alt='' src='./Map-sm.png' />
        <div id='g-ai1-1' className='g-ai2jsx-settings g-aiAbs g-aiPointText' style={{ top: '-3.2325%', marginTop: '-15.6px', left: '0%', width: '112px' }}>
          <p className='g-pstyle0'>300</p>
        </div>
        <div id='g-ai1-2' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '2.4072%', marginTop: '-20.1px', left: '50.0521%', marginLeft: '-132px', width: '264px' }}>
          <p className='g-pstyle1'>Change in Buttigieg&rsquo;s general</p>
          <p className='g-pstyle1'>election margin, 2011-2015</p>
        </div>
        <div id='g-ai1-3' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '9.6178%', marginTop: '-8.4px', left: '18.5023%', marginLeft: '-26px', width: '52px' }}>
          <p className='g-pstyle2'>&ndash;40%</p>
        </div>
        <div id='g-ai1-4' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '9.6178%', marginTop: '-8.4px', left: '34.5908%', marginLeft: '-26px', width: '52px' }}>
          <p className='g-pstyle2'>&ndash;20%</p>
        </div>
        <div id='g-ai1-5' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '9.6178%', marginTop: '-8.4px', left: '50.887%', marginLeft: '-19.5px', width: '39px' }}>
          <p className='g-pstyle2'>0%</p>
        </div>
        <div id='g-ai1-6' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '9.6178%', marginTop: '-8.4px', left: '66.4193%', marginLeft: '-26px', width: '52px' }}>
          <p className='g-pstyle2'>+20%</p>
        </div>
        <div id='g-ai1-7' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '9.6178%', marginTop: '-8.4px', left: '81.6042%', marginLeft: '-26px', width: '52px' }}>
          <p className='g-pstyle2'>+40%</p>
        </div>
        <div id='g-ai1-8' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '56.5477%', marginTop: '-20.1px', left: '49.9954%', marginLeft: '-135.5px', width: '271px' }}>
          <p className='g-pstyle1'>Vacant and abandoned houses</p>
          <p className='g-pstyle1'>targeted by the initiative</p>
        </div>
        <div id='g-ai1-9' className='g-ai2html-settings g-aiAbs g-aiPointText' style={{ top: '60.4527%', marginTop: '-8.4px', left: '50.0625%', marginLeft: '-108.5px', width: '217px' }}>
          <p className='g-pstyle2'>As identified by mayor&rsquo;s task force</p>
        </div>
      </div>
    </div>
  </div>
);

export default sm;
/* End ai2jsx - 2019-07-12 12:20 */
